version: 2.1

orbs:
  maven: circleci/maven@1.0.3

workflows:
  maven_test:
    jobs:
      - maven/test: # checkout, build, test, and upload test results
          command: '-X verify'
      - maven/site:
          command: '-X site'
      - maven/deploy:
          command: '-X deploy'

