version: 2.1

#orbs:
#  maven: circleci/maven@1.0.3
#
#workflows:
#  parallel_test:
#    jobs:
#      - maven/test: # checkout, build, test, and upload test results
#          command: '-X verify'
#    branches:
#      ignore:
#        - gh-pages
#        - mvn-repo

jobs:
  cache:
    branch: master
    steps:
      - checkout
      - run: mvn -DskipTests clean install dependency:resolve-plugins dependency:go-offline
  test:
    branch: master
    steps:
      - checkout
      - run: mvn -X verify
  site:
    branch: master
    steps:
      - checkout
      - run: mvn -X -DskipTests site
  deploy:
    branch: master
    steps:
      - checkout
      - run: mvn -X -DskipTests deploy

workflows:
  version: 2.1
  cache_and_test:
    jobs:
      - cache
      - test
          requires:
            - cache
      - site
          requires:
            - test
      - deploy
          requires:
            - test

