version: 2.1

#orbs:
#  maven: circleci/maven@1.0.3
#
#workflows:
#  parallel_test:
#    jobs:
#      - maven/test: # checkout, build, test, and upload test results
#          command: '-X verify'
#    branches:
#      ignore:
#        - gh-pages
#        - mvn-repo

jobs:
  cache:
    docker:
      - image: circleci/openjdk:stretch
    steps:
      - checkout
      - run: mvn -DskipTests clean install dependency:resolve-plugins dependency:go-offline
  test:
    docker:
      - image: circleci/openjdk:stretch
    steps:
      - checkout
      - run: mvn -X verify
  site:
    docker:
      - image: circleci/openjdk:stretch
    steps:
      - checkout
      - run: mvn -X -DskipTests site
  deploy:
    docker:
      - image: circleci/openjdk:stretch
    steps:
      - checkout
      - run: mvn -X -DskipTests deploy

workflows:
  version: 2.0
  do_everything:
    jobs:
      - cache:
          branches:
            ignore:
              - gh-pages
              - mvn-repo
      - test:
          requires:
            - cache
          branches:
            ignore:
              - gh-pages
              - mvn-repo
      - site:
          requires:
            - test
          branches:
            ignore:
              - gh-pages
              - mvn-repo
      - deploy:
          requires:
            - test
          branches:
            ignore:
              - gh-pages
              - mvn-repo

